"""users jwt

Revision ID: 15eb7df3b4e9
Revises: 7ced2685aa81
Create Date: 2022-10-14 16:55:07.041139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15eb7df3b4e9'
down_revision = '7ced2685aa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token')
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    # ### end Alembic commands ###
